# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build release on pull request

on:
  pull_request:
    branches: ["master"]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "Squeamish.sln"
  

permissions:
  contents: read

jobs:
  build:
    runs-on: [Windows, self-hosted]
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'FrancoisSuzeau/Squeamish'
        submodules: true
        lfs: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        vs-prerelease: true
        vs-version: '17.8.0'

    # - name: Build release
    #   working-directory: ${{env.GITHUB_WORKSPACE}}
    #   run: msbuild ${{env.SOLUTION_FILE_PATH}}

  publish:
    runs-on: [Windows, self-hosted]
    needs: build
    steps:
    - name: Send webhook
      shell: powershell
      run: |
        $body = gh api -H "Accept: application/vnd.github+json" -H "X-Github-Api-Version: 2022-11-28" /repos/FrancoisSuzeau/Squeamish/pulls/${{ github.event.pull_request.number }} | jq -r '.body'
        echo $body
        $issuenumber = [regex]::Match($body, '\d+').Value
        echo $issuenumber
#        $labels = gh api -H "Accept: application/vnd.github+json" -H "X-Github-Api-Version: 2022-11-28" /repos/FrancoisSuzeau/Squeamish/issues/${{ github.event.pull_request.number }}/labels | jq '[.[].name]'
#        echo $labels

      #  .github/workflows/send_webhook_pr.ps1 ${{ github.actor }} https://github.com/${{ github.actor }}.png?size=460 "${{ github.event.pull_request.title }}" $labels