# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build release on pull request

on:
  pull_request:
    branches: ["master"]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "Squeamish.sln"
  BRANCH_NAME: "${{ github.event.pull_request.head.ref }}"
  API_URL: "https://api.github.com/repos/${{ github.repository }}/issues"
  ISSUE_URL: "${{ github.event.pull_request.issue.url }}"

permissions:
  contents: read

jobs:
  build:
    runs-on: [Windows, self-hosted]
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: "${{ github.repository }}"
        submodules: true
        lfs: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        vs-prerelease: true
        vs-version: '17.8.0'

    # - name: Build release
    #   working-directory: ${{env.GITHUB_WORKSPACE}}
    #   run: msbuild ${{env.SOLUTION_FILE_PATH}}

  publish:
    runs-on: [Windows, self-hosted]
    needs: build
    steps:
    - name: Get Branch Name
      shell: powershell
      run: |
        echo "${{env.BRANCH_NAME}}"
        echo "${{env.API_URL}}"
        echo "${{env.ISSUE_URL}}"

    # - name: Send webhook
    #   shell: powershell
    #   run: .github/workflows/send_webhook_pr.ps1 ${{ github.actor }} https://github.com/${{ github.actor }}.png?size=460 "${{ github.event.pull_request.title }}"
