# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create a release

on:
  push:
    branches:
      - feature/**
      - bugfix/**
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]

jobs:
  create_release:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: [Windows, self-hosted]
    steps:
    - run: |
          $branchRef = $env:GITHUB_REF
          $branchName = $branchRef -replace '^refs/heads/', ''
          $branchName
          $prefix = $branchName -split '/' [0]
          if ($prefix -eq 'feature' -or $prefix -eq 'bugfix') {
            Write-Output "Branch Prefix: $prefix"
          } else {
            Write-Output "Branch prefix is not 'feature' or 'bugfix'."
          }

          $latestTag = gh api -H "Accept: application/vnd.github+json" -H "X-Github-Api-Version: 2022-11-28" repos/FrancoisSuzeau/Squeamish/tags | jq -r '.[0].name'
          $version = [regex]::Match($latestTag, '^v(\d+\.\d+\.\d+)').Groups[1].Value
          $versionComponents = $version -split '\.'
          $major = $versionComponents[0]
          $minor = $versionComponents[1]
          $patch = $versionComponents[2]
