# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create a release

on:
  push:
    branches:
      - feature/**
      - bugfix/**

jobs:
  create_release:
    runs-on: [Windows, self-hosted]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine branch and tag version
      shell: pwsh
      run: |
          $branchRef = $env:GITHUB_REF
          $branchName = $branchRef -replace '^refs/heads/', ''
          $branchName

          $latestTag = gh api -H "Accept: application/vnd.github+json" -H "X-Github-Api-Version: 2022-11-28" repos/FrancoisSuzeau/Squeamish/tags | jq -r '.[0].name'
          $version = [regex]::Match($latestTag, '^v(\d+\.\d+\.\d+)').Groups[1].Value
          $versionComponents = $version -split '\.'
          $major = $versionComponents[0]
          $minor = $versionComponents[1]
          $patch = $versionComponents[2]
