# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Merge into Master

on:
  workflow_run:
    workflows:
      - "Build debug on push"
    types:
      - completed
  # push:
  #   branches: ["master"]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "Squeamish.sln"

permissions:
  contents: read

jobs:
  build:
    runs-on: [Windows, self-hosted]

    steps:

    - name: Download Variable Artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}

    - name: Read Variable from File
      run: echo "Variable is $(cat my_variable.txt)"

    - name: Send webhook
      run: .github/workflows/send_webhook_pr.ps1 ${{ github.actor }} https://github.com/${{ github.actor }}.png?size=460 "Feature added :" ${{ github.ref }}